// import { Geist, Geist_Mono } from "next/font/google";
import DashBoradNavbar from "@/components/Dashboard/Navbar";
import DashBoardSidebar from "@/components/Dashboard/Sidebar";
import "../globals.css"
import { ThemeProvider } from "@/components/Provider/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/sonner";



export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const cookieStore = await cookies()
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
    return (

        <main>

            <ThemeProvider attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange>

               
                <SidebarProvider defaultOpen={defaultOpen}>

          
                    <main className=" w-full">
                     

                        <div className="">
                            {children}
                            <Toaster></Toaster>
                        </div>
                    </main>

                </SidebarProvider>



            </ThemeProvider>

          


        </main>

    );
}
